### PR TITLE
Add asset symbol and decimal for polkadex

### PR DESCRIPTION
**Pull request by ap211unitech**
In this PR, Assets Symbol and it's decimal added for Polkadex Network.

### CODE REVIEW

**Comment by dudo50** [comment]
Hey @ap211unitech , thamk you for your contribution! This will be merged and released either today or tommorow latest. (Waiting for this PR to be merged first https://github.com/paraspell/xcm-tools/pull/189#pullrequestreview-1990791910)

**Comment by dudo50** [comment]
Merging this. Will release soon and ping you afterward @ap211unitech .

**Comment by dudo50** [comment]
Hey @ap211unitech SDK is now released containing updated asset data on for your chain. 
https://github.com/paraspell/xcm-tools/pull/194#event-12440809379

**Comment by ap211unitech** [comment]
Thanks @dudo50

**Pull request merged**
